Add hook to format Javascript
This adds a hook that uses prettier to format any Javascript. Like
the other formatters, the version number is pinned down.

Additionally, Hazy.mjs is formatted.

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -2,8 +2,9 @@
 
 set -e
 
-ORMOLU_VERSION=0.8.0.2
+ORMOLU_VERSION='0.8.0.2'
 CABAL_GILD_VERSION='1.6.0.2'
+PRETTIER_VERSION='3.7.4'
 
 UNSTAGED_FILES=$(git diff --name-only)
 if [ -n "$UNSTAGED_FILES" ]; then
@@ -13,6 +14,7 @@ fi
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)
 HASKELL_FILES=$(echo "$STAGED_FILES" | grep -E '\.(hs|hs-boot)$' || true)
 CABAL_FILES=$(echo "$STAGED_FILES" | grep -E '\.cabal$' || true)
+JAVASCRIPT_FILES=$(echo "$STAGED_FILES" | grep -E '\.(js|mjs)$' || true)
 
 if [ -n "$HASKELL_FILES" ]; then
     if ! command -v ormolu &> /dev/null; then
@@ -38,12 +40,30 @@ if [ -n "$CABAL_FILES" ]; then
     fi
 fi
 
+if [ -n "$JAVASCRIPT_FILES" ]; then
+    if ! command -v prettier &> /dev/null; then
+        echo "Error: 'prettier' is not installed or not in your PATH."
+        exit 1
+    fi
+
+    if [ $(prettier --version) != $PRETTIER_VERSION ]; then
+        echo "Wrong 'prettier' version is installed."
+        exit 1
+    fi
+fi
+
 if [ -n "$CABAL_FILES" ]; then
     echo "=== Formatting Cabal ==="
     for FILE in $CABAL_FILES; do
         cabal-gild --io="$FILE" || echo "Error: Failed to format $FILE"
         git add "$FILE"
     done
+fi
+
+if [ -n "$JAVASCRIPT_FILES" ]; then
+    echo "=== Formatting Javascript ==="
+    prettier -w $JAVASCRIPT_FILES
+    git add $JAVASCRIPT_FILES
 fi
 
 if [ -n "$HASKELL_FILES" ]; then
